config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :order_lists
  resources :component_lists
  resources :words

  get '/words/generate/:name', to: 'words#generate'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order_list.rb
class OrderList < ApplicationRecord
  validates :name, presence: true
  validates :order, presence: true
end

app/controllers/order_lists_controller.rb
class OrderListsController < ApplicationController
  before_action :set_order_list, only: [:show, :edit, :update, :destroy]

  # GET /order_lists
  # GET /order_lists.json
  def index
    @order_lists = OrderList.all
  end

  # GET /order_lists/1
  # GET /order_lists/1.json
  def show
  end

  # GET /order_lists/new
  def new
    @order_list = OrderList.new
  end

  # GET /order_lists/1/edit
  def edit
  end

  # POST /order_lists
  # POST /order_lists.json
  def create
    @order_list = OrderList.new(order_list_params)

    respond_to do |format|
      if @order_list.save
        format.html { redirect_to @order_list, notice: 'Order list was successfully created.' }
        format.json { render :show, status: :created, location: @order_list }
      else
        format.html { render :new }
        format.json { render json: @order_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_lists/1
  # PATCH/PUT /order_lists/1.json
  def update
    respond_to do |format|
      if @order_list.update(order_list_params)
        format.html { redirect_to @order_list, notice: 'Order list was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_list }
      else
        format.html { render :edit }
        format.json { render json: @order_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_lists/1
  # DELETE /order_lists/1.json
  def destroy
    @order_list.destroy
    respond_to do |format|
      format.html { redirect_to order_lists_url, notice: 'Order list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_list
      @order_list = OrderList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_list_params
      params[:order_list][:order_array] = params[:order_list][:order].split(" ")
      params.require(:order_list).permit(:name, :order, :order_list)
    end
end

app/helpers/order_lists_helper.rb
module OrderListsHelper
end

app/views/order_lists/_form.html.erb
<%= form_with(model: order_list, local: true) do |form| %>
  <% if order_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_list.errors.count, "error") %> prohibited this order_list from being saved:</h2>

      <ul>
      <% order_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.text_area :order %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_lists/edit.html.erb
<h1>Editing Order List</h1>

<%= render 'form', order_list: @order_list %>

<%= link_to 'Show', @order_list %> |
<%= link_to 'Back', order_lists_path %>

app/views/order_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Lists</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Order array</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_lists.each do |order_list| %>
      <tr>
        <td><%= order_list.name %></td>
        <td><%= order_list.order %></td>
        <td><%= link_to 'Show', order_list %></td>
        <td><%= link_to 'Edit', edit_order_list_path(order_list) %></td>
        <td><%= link_to 'Destroy', order_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order List', new_order_list_path %>

app/views/order_lists/new.html.erb
<h1>New Order List</h1>

<%= render 'form', order_list: @order_list %>

<%= link_to 'Back', order_lists_path %>

app/views/order_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order_list.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_list.order %>
</p>

<%= link_to 'Edit', edit_order_list_path(@order_list) %> |
<%= link_to 'Back', order_lists_path %>