config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :order_lists
  resources :component_lists
  resources :words

  get '/words/generate/:name', to: 'words#generate'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/component_list.rb
class ComponentList < ApplicationRecord
  validates :name, presence: true
  validates :components, presence: true, format: { with: /\A[a-zA-Z ]+\z/,
    message: "word components only allow letters" }
end

app/controllers/component_lists_controller.rb
class ComponentListsController < ApplicationController
  before_action :set_component_list, only: [:show, :edit, :update, :destroy]

  # GET /component_lists
  # GET /component_lists.json
  def index
    @component_lists = ComponentList.all
  end

  # GET /component_lists/1
  # GET /component_lists/1.json
  def show
  end

  # GET /component_lists/new
  def new
    @component_list = ComponentList.new
  end

  # GET /component_lists/1/edit
  def edit
  end

  # POST /component_lists
  # POST /component_lists.json
  def create
    @component_list = ComponentList.new(component_list_params)

    respond_to do |format|
      if @component_list.save
        format.html { redirect_to @component_list, notice: 'Component list was successfully created.' }
        format.json { render :show, status: :created, location: @component_list }
      else
        format.html { render :new }
        format.json { render json: @component_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /component_lists/1
  # PATCH/PUT /component_lists/1.json
  def update
    respond_to do |format|
      if @component_list.update(component_list_params)
        format.html { redirect_to @component_list, notice: 'Component list was successfully updated.' }
        format.json { render :show, status: :ok, location: @component_list }
      else
        format.html { render :edit }
        format.json { render json: @component_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /component_lists/1
  # DELETE /component_lists/1.json
  def destroy
    @component_list.destroy
    respond_to do |format|
      format.html { redirect_to component_lists_url, notice: 'Component list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_component_list
      @component_list = ComponentList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def component_list_params
      params[:component_list][:components_array] = params[:component_list][:components].split(" ")
      params.require(:component_list).permit(:name, :components, :components_array)
    end
end

app/helpers/component_lists_helper.rb
module ComponentListsHelper
end

app/views/component_lists/_form.html.erb
<%= form_with(model: component_list, local: true) do |form| %>
  <% if component_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(component_list.errors.count, "error") %> prohibited this component_list from being saved:</h2>

      <ul>
      <% component_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :components %>
    <%= form.text_area :components %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/component_lists/edit.html.erb
<h1>Editing Component List</h1>

<%= render 'form', component_list: @component_list %>

<%= link_to 'Show', @component_list %> |
<%= link_to 'Back', component_lists_path %>

app/views/component_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Component Lists</h1>

<table>
  <thead>
    <tr>
      <th>Components</th>
      <th>Components array</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @component_lists.each do |component_list| %>
      <tr>
        <td><%= component_list.name %></td>
        <td><%= component_list.components %></td>
        <td><%= link_to 'Show', component_list %></td>
        <td><%= link_to 'Edit', edit_component_list_path(component_list) %></td>
        <td><%= link_to 'Destroy', component_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Component List', new_component_list_path %>

app/views/component_lists/new.html.erb
<h1>New Component List</h1>

<%= render 'form', component_list: @component_list %>

<%= link_to 'Back', component_lists_path %>

app/views/component_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @component_list.name %>
</p>

<p>
  <strong>Components:</strong>
  <%= @component_list.components %>
</p>

<%= link_to 'Edit', edit_component_list_path(@component_list) %> |
<%= link_to 'Back', component_lists_path %>