config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :order_lists
  resources :component_lists
  resources :words

  get '/words/generate/:name', to: 'words#generate'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words/generate/:name
  # GET /words/generate/:name.json
  def generate
    @order_list = OrderList.find_by(name: params[:name])
    @order_array = @order_list[:order].split(" ")

    word = ""
    for component in @order_array
      component_obj = ComponentList.find_by(name: component)
      comp_array = component_obj[:components].split(" ")
      word << comp_array.sample
    end
    @word = word
  end

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
    words = helpers.file_to_word_array('app/helpers/words30.txt')
    all_words_dict = helpers.nth_markov_dictograms(words, 2)
    @gen_word = helpers.nth_markov_chain(all_words_dict, 5)
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word, :votes)
    end
end

app/helpers/words_helper.rb
module WordsHelper
  def file_to_word_array(file_path)
    words = Array.new

    File.open(file_path, "r") do |f|
      f.each_line do |line|
        words.push(line.gsub("\n",''))
      end
    end

    words
  end

  class Dictogram < Hash

    def initialize(word = nil)
      @types = 0
      @tokens = 0

      if word != nil
        @tokens += word.length

        word.each_char do |chr|
          if self.key?(chr)
            self[chr] += 1
          else
            self[chr] = 1
            @types += 1
          end

        end
      end
    end

    def add_count(letter, count = 1)
      @tokens += count

      if self.key?(letter)
        self[letter] += 1
      else
        self[letter] = 1
        @types += 1
      end
    end

    def frequency(letter)
      if self.key?(letter)
        self[letter]
      else
        0
      end
    end

  end

  def nth_markov_dictograms(text_array, nth_order)
    dictogram_hash = Hash.new

    for word in text_array
      if word.length <= nth_order
        next
      else
        last_index = text_array.length - nth_order
        for char_index in 0...last_index
          nth_char = char_index + nth_order
          current_letters = word[char_index...nth_char]
          next_letter = word[char_index + nth_order]

          if next_letter != nil
            if dictogram_hash.key?(current_letters)
              dictogram_hash[current_letters].add_count(next_letter)
            else
              dictogram_hash[current_letters] = Dictogram.new(next_letter)
            end
          end

        end
      end
    end

    dictogram_hash
  end

  def weighted_dict_sampling(dictogram)
    list_of_prefixes = dictogram.keys

    total_tokens = 0
    for prefix in list_of_prefixes
      total_tokens += dictogram[prefix]
    end

    prng = Random.new
    random_num = prng.rand(0...total_tokens)

    dictogram.each do |prefix, value|
      word_frequency = value

      while word_frequency > 0
        if random_num > 0
          random_num -= 1
          word_frequency -= 1
        else
          return prefix
        end
      end

    end
  end

  def nth_markov_chain(dictogram_dictionary, length)
    hash_keys = dictogram_dictionary.keys
    word = ""
    word << hash_keys.sample.clone
    nth_order = word.length

    last_index = length - nth_order
    for char_index in 0...last_index
      nth_char = char_index + nth_order
      prefix_key = word[char_index...nth_char]

      if dictogram_dictionary.key?(prefix_key)
        char_dictogram = dictogram_dictionary[prefix_key]
        next_char = weighted_dict_sampling(char_dictogram)
        word << next_char
      else
        break
      end
    end

    word
  end
end

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :word %>
    <%= form.text_field :word %>
  </div>

  <div class="field">
    <%= form.label :votes %>
    <%= form.number_field :votes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/generate.html.erb
<p><%= @word %></p>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Votes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word %></td>
        <% if false %>
          <td><%= word.word %></td>
          <td><%= word.votes %></td>
        <% end %>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @word.votes %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>